name: Go Build and Test

on:
  workflow_call:

jobs:
  # Build and test validation for all pushes and PRs
  build-and-test:
    runs-on: ubuntu-latest
    inputs:
      matrix:
        description: 'Matrix of projects to build and test'
        required: true
        type: json
    strategy:
      fail-fast: true
      matrix: ${{ fromJSON(inputs.matrix) }}
    steps:
      - name: Download dependencies for ${{ matrix.project }}
        run: |
          cd ${{ matrix.project }}
          go mod download
          go mod verify

      - name: Build ${{ matrix.project }}
        run: |
          cd ${{ matrix.project }}
          echo "Building ${{ matrix.project }}..."
          go build -v ./...
          echo "✅ Build successful for ${{ matrix.project }}"

      - name: Run tests for ${{ matrix.project }}
        run: |
          cd ${{ matrix.project }}
          echo "Running tests for ${{ matrix.project }}..."
          go test -v -coverprofile=coverage.out ./...
          echo "✅ Tests passed for ${{ matrix.project }}"

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.project }}
          path: ${{ matrix.project }}/coverage.out
          retention-days: 7