// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package v2_0_0

// Payment information for an order (v2)
type Payment struct {
	// Amount corresponds to the JSON schema field "amount".
	Amount float64 `json:"amount" yaml:"amount" mapstructure:"amount"`

	// Method corresponds to the JSON schema field "method".
	Method string `json:"method" yaml:"method" mapstructure:"method"`

	// OrderId corresponds to the JSON schema field "orderId".
	OrderId int `json:"orderId" yaml:"orderId" mapstructure:"orderId"`

	// PaymentId corresponds to the JSON schema field "paymentId".
	PaymentId int `json:"paymentId" yaml:"paymentId" mapstructure:"paymentId"`

	// Status corresponds to the JSON schema field "status".
	Status *PaymentStatus `json:"status,omitempty" yaml:"status,omitempty" mapstructure:"status,omitempty"`
}

type PaymentStatus string

const PaymentStatusCompleted PaymentStatus = "completed"
const PaymentStatusFailed PaymentStatus = "failed"
const PaymentStatusPending PaymentStatus = "pending"
