name: Matrix execution

on:
  workflow_call:

jobs:
  matrix-definition:
    strategy:
      fail-fast: true
      matrix:
        project: [utils, schemas, stream-buffer, stream-consumer, schema-validator, schema-repository, kafka-consumer, kafka-producer]
    uses: ./.github/workflows/go-build-test
    with:
      project: ${{ matrix.project }}