// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package v1_0_0

// A user's address
type Address struct {
	// City corresponds to the JSON schema field "city".
	City string `json:"city" yaml:"city" mapstructure:"city"`

	// PostalCode corresponds to the JSON schema field "postalCode".
	PostalCode string `json:"postalCode" yaml:"postalCode" mapstructure:"postalCode"`

	// Street corresponds to the JSON schema field "street".
	Street string `json:"street" yaml:"street" mapstructure:"street"`
}
