// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package v1_0_0

// A product in the catalog
type Product struct {
	// Category corresponds to the JSON schema field "category".
	Category *string `json:"category,omitempty" yaml:"category,omitempty" mapstructure:"category,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id int `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Price corresponds to the JSON schema field "price".
	Price float64 `json:"price" yaml:"price" mapstructure:"price"`
}
