// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package v1_0_0

// A user of the system
type User struct {
	// Email of the user
	Email string `json:"email" yaml:"email" mapstructure:"email"`

	// The unique identifier for a user
	Id int `json:"id" yaml:"id" mapstructure:"id"`

	// Name of the user
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}
