---
kc:
  log:
    level: "debug"
  maxProcessRoutines: 50
  partitionRecordsChannelSize: 10
  closeTimeout: 1m
  kafka:
    group: "feijoada-consumer-group"
  repository:
    stream:
      name: "feijoada-stream"
      group: "feijoada-stream-group"
      readCount: 100
      block:  100ms