// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package v2_0_0

// A user's address (v2)
type Address struct {
	// City corresponds to the JSON schema field "city".
	City string `json:"city" yaml:"city" mapstructure:"city"`

	// Country corresponds to the JSON schema field "country".
	Country *string `json:"country,omitempty" yaml:"country,omitempty" mapstructure:"country,omitempty"`

	// PostalCode corresponds to the JSON schema field "postalCode".
	PostalCode string `json:"postalCode" yaml:"postalCode" mapstructure:"postalCode"`

	// Street corresponds to the JSON schema field "street".
	Street string `json:"street" yaml:"street" mapstructure:"street"`
}
