// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package v2_0_0

// An order placed by a user (v2)
type Order struct {
	// OrderId corresponds to the JSON schema field "orderId".
	OrderId int `json:"orderId" yaml:"orderId" mapstructure:"orderId"`

	// ProductIds corresponds to the JSON schema field "productIds".
	ProductIds []int `json:"productIds" yaml:"productIds" mapstructure:"productIds"`

	// Status corresponds to the JSON schema field "status".
	Status *OrderStatus `json:"status,omitempty" yaml:"status,omitempty" mapstructure:"status,omitempty"`

	// Total corresponds to the JSON schema field "total".
	Total float64 `json:"total" yaml:"total" mapstructure:"total"`

	// UserId corresponds to the JSON schema field "userId".
	UserId int `json:"userId" yaml:"userId" mapstructure:"userId"`
}

type OrderStatus string

const OrderStatusCancelled OrderStatus = "cancelled"
const OrderStatusDelivered OrderStatus = "delivered"
const OrderStatusPending OrderStatus = "pending"
const OrderStatusShipped OrderStatus = "shipped"
