name: Setup Go Environment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matrix-definition:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"utils\"},{\"project\":\"schemas\"}]}" >> $GITHUB_OUTPUT

  # Setup go and cache modules for all projects
  setup-go:
    needs: matrix-definition
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'utils/go.mod'
          check-latest: true
          cache-dependency-path: |
            utils/go.sum
            schemas/go.sum
            stream-buffer/go.sum
            stream-consumer/go.sum
            schema-validator/go.sum
            schema-repository/go.sum
            kafka-consumer/go.sum
            kafka-producer/go.sum

      - name: Run build and test
        with:
          matrix: ${{ needs.matrix-definition.outputs.matrix }}
        uses: ./.github/workflows/go-build-test